Update setup script

diff --git a/boilerplate/bin/setup b/boilerplate/bin/setup
--- a/boilerplate/bin/setup
+++ b/boilerplate/bin/setup
@@ -5,6 +5,12 @@
 # Runs all the needed commands to set up a developer's system to run this app.
 # Customize this as your app grows.
 
+# Check for macOS
+if [[ ! "$OSTYPE" =~ ^darwin ]]; then
+  echo "This script only works on macOS"
+  exit 1
+fi
+
 # Check for Homebrew
 command -v brew >/dev/null 2>&1 || {
   echo "This setup script requires Homebrew, but it was not found on your system."
@@ -43,12 +49,35 @@ command -v yarn >/dev/null 2>&1 || {
 # Ensure react-native-cli is installed
 command -v react-native >/dev/null 2>&1 || {
   echo "This app requires react-native-cli, but it was not found on your system."
-  echo "Installing react-native-cli globally with npm..."
-  npm install -g react-native-cli
+  echo "Installing react-native-cli globally with yarn..."
+  yarn global add react-native-cli
 }
 
+# IF NEEDED: Ensure appleSimUtils is installed
+# command -v applesimutils >/dev/null 2>&1 || {
+#   echo "This app requires appleSimUtils to run end to end tests, but it was not found on your system."
+#   echo "Installing applesimutils with brew..."
+#   brew tap wix/brew
+#   brew install applesimutils
+# }
+
+# IF NEEDED: Ensure detox-cli is installed
+# command -v detox >/dev/null 2>&1 || {
+#   echo "This app requires detox-cli to run end to end tests, but it was not found on your system."
+#   echo "Installing detox globally with npm..."
+#   npm install -g detox-cli
+# }
+
+# IF NEEDED: Ensure phraseapp is installed
+# command -v phraseapp >/dev/null 2>&1 || {
+#   echo "This app requires phraseapp to run localizations, but it was not found on your system."
+#   echo "Installing phraseapp with brew..."
+#   brew tap phrase/brewed
+#   brew install phraseapp
+# }
+
 echo "----------------------------------------------------------"
-echo "Installing NPM Packages"
+echo "Installing NPM Packages with Yarn"
 echo "----------------------------------------------------------"
 
 yarn || { echo "NPM Packages could not be installed!"; exit 1; };
@@ -61,6 +90,19 @@ cd ios/ && {
   pod install || { echo "CocoaPods could not be installed!"; exit 1; };
   cd -
 }
+
+# IF NEEDED
+# echo "----------------------------------------------------------"
+# echo "Running localizations"
+# echo "----------------------------------------------------------"
+
+# bin/localize
+
+echo "----------------------------------------------------------"
+echo "Running tests to verify setup is complete"
+echo "----------------------------------------------------------"
+
+yarn test || { exit 1; }
 
 echo "----------------------------------------------------------"
 echo "Setup complete!"
